### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by Vinayak119A** [jzheng2017/spotify-web-api-wrapper#65]
Hey, I am Vinayak Kanjiker I would like to contribute in this app can you please assign me a task .
This is for my open source contribution class.
please contact me at vinukanjiker@gmail.com

**Comment by jzheng2017** [comment]
Hi Vinayak, are you still looking for a task to contribute to?

**Comment by Apoorvasaxena** [comment]
Hi @jzheng2017, I am interested in making a contribution to this project. I have about 7 years of experience in building backend services but am new to open-source contributions. Is there anything here that I can help with?

**Comment by jzheng2017** [comment]
Hi @Apoorvasaxena, please see the list here https://github.com/jzheng2017/spotify-web-api-wrapper/issues. Pick anything you'd like to do.
